/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ShowsLazyImport = createFileRoute('/shows')()
const ProjectsLazyImport = createFileRoute('/projects')()
const GamesLazyImport = createFileRoute('/games')()

// Create/Update Routes

const ShowsLazyRoute = ShowsLazyImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/shows.lazy').then((d) => d.Route))

const ProjectsLazyRoute = ProjectsLazyImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))

const GamesLazyRoute = GamesLazyImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/games.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyImport
      parentRoute: typeof rootRoute
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/shows': typeof ShowsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/shows': typeof ShowsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/games': typeof GamesLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/shows': typeof ShowsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games' | '/projects' | '/shows'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games' | '/projects' | '/shows'
  id: '__root__' | '/' | '/games' | '/projects' | '/shows'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesLazyRoute: typeof GamesLazyRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
  ShowsLazyRoute: typeof ShowsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesLazyRoute: GamesLazyRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
  ShowsLazyRoute: ShowsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/games",
        "/projects",
        "/shows"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/games": {
      "filePath": "games.lazy.tsx"
    },
    "/projects": {
      "filePath": "projects.lazy.tsx"
    },
    "/shows": {
      "filePath": "shows.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
